### ISSUE TITLE
OAuth Proxy not accepting external traffic

### ISSUE THREAD

**Issue by edhgoose** [bitly/oauth2_proxy#118]
Hi,

I apologise for this as I'm sure I must be doing something wrong, but here we go.

I downloaded and setup the oauth proxy to use with a Google account. After following the various instructions, I ran a command roughly like:

`./oauth2_proxy -upstream="http://localhost:9000" --client-id="my-client-id.apps.googleusercontent.com" --client-secret="my-secret" --cookie-secret="this is a cookie secret for this server"`.

I then executed `curl localhost:4180/ping` and got a 200 response as expected.

I ensured that I opened up the security groups on my instance and tried to access it from my local machine. But I only got `connection refused`.

Skipping a long story, I ended up compiling the simple Go server which is currently here: https://golang.org/doc/articles/wiki/#tmp_3, with a minor modification to use port 4180 instead of 8080.

And everything worked. I could access my Simple Go Server from both localhost (same machine) and from my own dev machine. Which, I think, rules out any firewalls, security groups etc. But possibly doesn't rule out issues with the Amazon AMI I'm using.

I began digging around in the code for the server, and found that the primary difference is this one:

In `http.go`, the current code executes:

`listener, err := net.Listen(networkType, listenAddr)`, which translated to: `listener, err := net.Listen("tcp", "127.0.0.1:4180")`

Whereas the Simple Go Server executes something equivalent to `net.Listen("tcp", ":4180")`.

Changing the code in `http.go` to:

`listener, err := net.Listen(networkType, ":4180")` fixed the problem.

And equally, changing my Simple Go Server to `net.Listen("tcp", "127.0.0.1:4180")` breaks it. I'm running Go v1.4.2 if that's relevant.

So it's something about how that listener gets setup.

So, I think the bug is either:
1. You can't set -http-address=":4180", which I think would solve my problem.
2. Some documentation about what issue I've run into and how to resolve it.

I'm assuming it's some configuration issue around networking I'm not familiar with and therefore the solution is 2. If someone can point me in the right direction that'd be fantastic!

Thanks!

Ed

**Comment by ploxiln** [comment]
It's expected that you either configure oauth2_proxy to do TLS itself (specify --tls-cert and --tls-key) or use an http proxy like nginx in front of oauth2_proxy, and have that http proxy terminate TLS. That's why oauth2_proxy by default only listens on 127.0.0.1 which only allows connections from processes on the same server (for example, nginx running on the same server and listening for https connections). see https://github.com/bitly/oauth2_proxy#ssl-configuration

I expect that if you specify `--http-address=0.0.0.0:4180` you can force oauth2_proxy to accept http connections on any interface.

**Comment by jehiah** [comment]
The docs could probably be clearer here. As @ploxiln beat me to, you want `0.0.0.0:4180` The `0.0.0.0` denoting to listen on any ip.

The form for listening is a little finicky because it expects a protocol so it can pivot and listen on a socket. That means `http://:4180` will also work.

please confirm back here that those details solve your issue.

**Comment by edhgoose** [comment]
Ah, it's so obvious!

Yes, that is exactly what I needed. I'm using Amazon ELB as my termination point, hence the problem. Let me update the docs.
