### ISSUE TITLE
Use with the Nginx auth_request directive

### ISSUE THREAD

**Issue by MiguelGArgiles** [bitly/oauth2_proxy#169]
Hi

I am trying to configure oauth2_proxy with nginx using auth_request directive but I am not able to find the way to make it works.

In our system, nginx works as a reverse proxy for several Atlassian Tools (JIRA, Bamboo). We want nginx to call oauth2_proxy to authenticate users.

Nginx seems to redirect requests well to oauth2_proxy but oauth2_proxy always answers with a 403.

Our nginx has been configured with the following values:

    location = /auth {
        internal;
        proxy_pass http://127.0.0.1:4180;
    }

    location /ansible_jenkins {
      auth_request /auth;
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
       .....

oauth2_proxy logs the following message

127.0.0.1 - - [15/Nov/2015:00:38:24 +0000] 127.0.0.1:4180 GET - "/auth" HTTP/1.0 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36" 403 2288 0.001

Thanks for your help !!

**Comment by mbland** [comment]
Are you using the latest `master`, with commit https://github.com/bitly/oauth2_proxy/commit/7c241ec1fe047b5c4a07185f7474d455e4db057a? The `/auth` endpoint isn't in any official releases yet.

**Comment by jehiah** [comment]
@MiguelGArgiles thanks opening this issue. `auth_module` support is relatively new (as of #153) so this might be an indication of some rough edges.

@mbland correct me if i'm wrong, but i think the actual endpoint needs to be configured as `/oauth2/auth` unless you use a non-default proxy prefix like `-proxy-prefix=/`

```
location = /oauth2/auth {
    internal;
    proxy_pass http://127.0.0.1:4180;
    proxy_set_header X-Real-IP $remote_addr;
}
location /... {
    auth_request /oauth2/auth;
    ...
}
```

I think you also need to proxy `/oauth2` for actually signing in. Right @mbland ? 

```
location /oauth2 {
        proxy_pass http://127.0.0.1:4180;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
}
```

**Comment by mbland** [comment]
Yeah, @jehiah, I think you're right. In my current configuration I'm using an [18F/authdelegate](https://github.com/18F/authdelegate/) server that is itself configured to proxy to `/oauth2/auth`, which is why I forgot to reflect the `/oauth2` prefix in the README here. I think proxying to `/oauth2` to log in is also correct, and can even work with `error_page 401 /oauth2`. I'll be happy to try this out in the next couple days and fix up the README, if you want to assign this issue to me.

**Comment by MiguelGArgiles** [comment]
Hi @jehiah and @mbland

Thank to your help, I finally managed to fix it.
As you pointed out, I made two mistakes:

- I was using the last release instead of last master commit. 
- My nginx config file had mistakes.

As I said thank you for your help

**Comment by eldadh** [comment]
I am also trying to use Use with the Nginx auth_request directive function
since the oauth2_proxy doesn't have streaming capabilities yet ( i need those for guacamole web app).

i keep getting internal errors when trying to use the given setup ( in the readme) and after reading the post/issues in the git.

my guess is wrong oauth config but i didnt find what.
like i said i would like the nginx to authenticate via oauth2_proxy 
and proxy the data itself 

my nginx is as fallows:
`    server
    {
        listen          443 ssl; 
 
        ### SSL cert files ###
        ssl_certificate      *********************;
        ssl_certificate_key  *********************;


        ### Add SSL specific settings here ###
        ssl_protocols        TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers RC4:HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        keepalive_timeout    60;
        ssl_session_cache    shared:SSL:10m;
        ssl_session_timeout  10m;
	
	root /var/www/html;

	charset utf-8;
	charset_types application/json utf-8;

	location = /oauth2/auth {
	   internal;
	   proxy_set_header Host $host;
	   proxy_set_header X-Real-IP $remote_addr;
	   proxy_set_header X-Scheme $scheme;
	   proxy_set_header X-Original-URI $request_uri;
	   proxy_pass_request_body off;
	   proxy_pass http://127.0.0.1:4180;

	}

	location /oauth2 {
	   proxy_set_header Host $host;
	   proxy_set_header X-Real-IP $remote_addr;
	   proxy_set_header X-Scheme $scheme;
	   proxy_set_header X-Original-URI $request_uri;
	   proxy_pass http://127.0.0.1:4180;
	   proxy_http_version 1.1;
	   proxy_set_header Connection "";
	}

	location / {
		auth_request /oauth2/auth;
		error_page 401 = https://127.0.0.1:4443/oauth2/sign_in;
		
		proxy_pass http://127.0.0.1:8080/;
		proxy_redirect off;
		proxy_buffering off;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $http_connection;
		proxy_cookie_path /guacamole/ /;
		access_log off;
        }
    }
}`

and my oauth2 config:
`http_address = ":4180"
https_address = ":4443"

## TLS Settings
tls_cert_file = "CRTCRTCRT"
tls_key_file = "KEYKEYKEY"

upstreams = [
     "http://127.0.0.1:8080/"
]

request_logging = true

email_domains = [
     "mydomain.com"
 ]

## The OAuth Client ID, Secret
client_id = "ZZZ.apps.googleusercontent.com" 
client_secret = "YYY" 

## Pass OAuth Access token to upstream via "X-Forwarded-Access-Token"
pass_access_token = true

cookie_name = "_oauth2_proxy"
cookie_secret = "ZZZZZ"
# cookie_domain = ""
cookie_expire = "24h"
# cookie_refresh = ""
cookie_secure = true
cookie_httponly = true
`
