### ISSUE TITLE
[Google] Cannot redeem token

### ISSUE THREAD

**Issue by vic3lord** [bitly/oauth2_proxy#252]
I'm using oauth2_proxy behind nginx+TLS, I did not get the app to work.

Getting the following error: error redeeming code Post https://www.googleapis.com/oauth2/v3/token: x509: failed to load system roots and no roots provided

Also trying to debug the app on my desktop (without nginx and using /etc/hosts), getting authentication complete but the cookie isn't set

**Comment by vic3lord** [comment]
Found the issue on my side; sorry

**Comment by ThatsNinja** [comment]
@vic3lord can you say what the issue was? I'm getting something similar with the Github provider:
```
error redeeming code Post https://github.com/login/oauth/access_token: x509: failed to load system roots and no roots provided
```

**Comment by vic3lord** [comment]
@ThatsNinja wow man I'm really sorry I didn't document it, I don't remember what it was, but I can help you if you can elaborate more... maybe configuration etc.

**Comment by ThatsNinja** [comment]
@vic3lord So, it turned out that I was doing something foolish: I'd created a container image to vendor the compiled oauth2_proxy binary, and to contain confd and associated templates for dynamic configuration. I was spinning that container up, executing confd against the running environment, and mounting its volumes into a bare-bones alpine container to actually run the binary, and the alpine image doesn't have CA certs in it.

In the end, my solution was to gang the same image together with one instance handling the config generation, and the other running the binary/hosting the service. My image is based on the golang-1.6 image, and so it came with the `ca-certificates` package installed. Problem solved.

**Comment by vic3lord** [comment]
`apk add ca-certificates` would have done the same trick for you but the image would be much smaller... (I used some other pipeline to compile the binary and then just `COPY` it to the container

I'm happy you solved it

**Comment by ThatsNinja** [comment]
Yes, good point. In my case, since I'm already grabbing down my configuration container image, and it's got everything it needs, I was able to actually cut some weight by just kicking alpine out of the car.

Thanks for getting back to me!

**Comment by vic3lord** [comment]
No problem, hope I helped
