### ISSUE TITLE
group-based authentication

### ISSUE THREAD

**Issue by jakeyr** [bitly/oauth2_proxy#28]
It would be great to leverage the google apps provisioning API to retrieve the logged-in user's group memberships, enabling some useful features:

  * Restricting access to an application/upstream by group.
  * Passing the list of group memberships foward in a header to the application, allowing for finer grained access control.

**Comment by vigoatrook** [comment]
We are using bitly proxy and it works well for basic OAuth. Now we are trying to get group and orgUnits information and apply cascaded privileges to a user.  The problem with using a file is that the list may not be in sync with Google, since positions can change within the organization, and security concerns, as anyone gains access to the server can change that file. I'm really tempted to implement this feature but like @jakeyr I'm also new to Go. I have a couple of questions from browsing the source. Would you kindly provide some guidance? Thanks

**Comment by jakeyr** [comment]
Since I last looked at this, it appears the google admin SDK has added the ability to enumerate members of a group:

https://developers.google.com/admin-sdk/directory/v1/reference/members/list

it also appears to have been added to the go client:

https://code.google.com/p/google-api-go-client/source/browse/admin/directory_v1/admin-api.json

the new scope is:

https://www.googleapis.com/auth/admin.directory.group.readonly

i can take a crack at implementing this now! hopefully i'll have some time tomorrow or this weekend for this.

**Comment by jakeyr** [comment]
@jehiah can you reopen this issue?

thanks!

**Comment by jehiah** [comment]
This capability was added in #139
