### ISSUE TITLE
oauth2 access token is printed to log by default

### ISSUE THREAD

**Issue by nickmiller-wf** [bitly/oauth2_proxy#291]
After setting a Cookie refresh value and setting `--pass-access-token` to true, we've noticed some logs come through that contain the access token, with no apparent way to turn it off.

See: https://github.com/bitly/oauth2_proxy/blob/master/providers/internal_util.go#L31

The `endpoint` var gets set to the fully qualified URL, which contains the `access_token` query parameter. For us, this doesn't pose a security threat as the default (GitHub) token scopes are `user:email` and `read:org`, both read-only.

But, if our application were to request a much larger scope, such as `repo` (full read/write to repositories) this would become a larger issue, especially once private repos get involved.

Am I missing some configuration here? It seems like an option should exist to turn this output off.

**Comment by jehiah** [comment]
@nickmiller-wf indeed. logging is hard. 

I'd be happy to accept a PR that redact's tokens (i.e. replacing half of them with `....` in the log line) in that and a few other logging lines for requests against OAuth providers. 

There isn't currently a pattern of changing the amount of logging for upstream requests or general internal logging, so that would probably need some larger refactoring.
