### ISSUE TITLE
`502 Bad Gateway` error when trying to run nginx with oauth2_proxy 

### ISSUE THREAD

**Issue by adishap** [bitly/oauth2_proxy#315]
I am getting error in nginx when I try to run `oauth2_proxy` with nginx.
```
2016/11/01 10:17:55 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:4180/", host: "localhost:81"
172.17.0.1 - - [01/Nov/2016:10:17:55 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
```

nginx.conf
```
events {
    worker_connections 1024;
}
http {
  server {
    listen 81
    location / {
      proxy_pass http://127.0.0.1:4180;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Scheme $scheme;
    }
  }
}
```

oauth2_proxy.cfg
```
provider = "github"
redirect_url = "http://localhost:8080/oauth2/callback/"
skip_provider_button = "true"
upstreams = ["http://localhost:8080/test"]
email_domains = ["*"]
client_id = "<client_id>"
client_secret = "<client_secret>"
cookie_name = "_oauth2_proxy"
cookie_secret = "+/grOZYJXcsGR96UrIs/Fw=="
cookie_secure = false
```

Thanks for the help!

**Comment by robin900** [comment]
@adishap We have noticed the same behavior for our new deployment of nginx and oauth2_proxy. We notice that the *first* authentication for a given google apps user results in the user landing at http://ourhost/# instead of the expected redirect to http://ourhost/ourapp# and the response is a 502 from nginx. Then on subsequent visits, the user is properly redirected to http://ourhost/ourapp (no # fragment). Then, if the same user opens an incognito browser and goes through the entire oauth flow a second time, the 502 error does not occur. 

Is this what you observed? And did you close this issue because the 502 problem went away after the user's first successful oauth flow?

**Comment by adishap** [comment]
@robin900 I did not noticed the same behavior. In my case the issue was that I was nginx using docker and trying to run oauth2_proxy on server therefore it was not finding ouath2_proxy's port. I resolved this problem by running both nginx and ouath2_proxy on server. If it helps, I can share my nginx configuration file.
