### ISSUE TITLE
Relative path for authenticated emails in docker container

### ISSUE THREAD

**Issue by tdorsey** [bitly/oauth2_proxy#337]
## Version Info:
oauth2_proxy: 2.2.0-alpha
docker: 1.12.3
## Issue
Outside of docker, I can use an authenticated email list correctly. 

 _validator.go:23: using authenticated emails file allowed_emails
 watcher.go:67: watching allowed_emails for updates_

When oauth2 is run from inside the docker container, I receive the following:

 _validator.go:23: using authenticated emails file allowed_emails
 watcher.go:66: failed to add allowed_emails to watcher: no such file or directory

The docker container is mounted with a data volume containing the oauth2 config file and allowed_emails in the same directory.

## Config file snippet
authenticated_emails_file = "allowed_emails"

## Notes
Specifying an absolute path from inside the container does work, but a path relative to the configuration file does not

**Comment by sellers** [comment]
Are you able to mount the file as a volume into your docker container?   Otherwise, there is no way they container will have the file, unless you added it to your image?   Are you trying to do this with K8S?  If so, you can create a configMap as a pipe, and then create a Volume map to mount the volume from a Configmap, and then mount that VolumeMap to /your/volume/mount, and then pass --authorized-emails-file=/your/volume/mount/name_in_configmap.txt.   name_in_configmap.txt is what you have for the data section in the configmap. 
```kind: ConfigMap
metadata:
  name: my-config
apiVersion: v1
data:
  name_in_configmap.txt: |-
    name
    list
    rows
    of_data
    here
```

**Comment by tdorsey** [comment]
As I mentioned above, the allowed emails file is volume mounted to the same directory as the config file. Unfortunately, this isn't in K8S, just a straight docker-compose. Thanks for the help, but I've since moved to a different tool. Closing due to age.
