### ISSUE TITLE
--skip-provider-button not working

### ISSUE THREAD

**Issue by Sneko** [bitly/oauth2_proxy#462]
Hi!

I tried parameter "--skip-provider-button" and "--skip-provider-button=true" but none of them seems to work :(

I'm currently using v2.2. Does anyone have information about that? Thanks :)

**Comment by ploxiln** [comment]
There are many different ways to setup and use oauth2_proxy. In some cases --skip-provider-button is useful. It is unclear what your situation is. But it might be related to #407 (which was merged after v2.2 was tagged and thus is not included in v2.2).

**Comment by Sneko** [comment]
@ploxiln  I'm using Kubernetes and I have read the following guide to set up oauth2_proxy (and the one of this repo because I'm using Google) : 
https://github.com/kubernetes/ingress/tree/master/examples/external-auth/nginx

For my global router (Ingress), I use these annotations: 
    ingress.kubernetes.io/auth-signin: "https://$host/oauth2/sign_in"
    ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"

And there are my oauth2_proxy settings at launch: 
`        - --provider=google
        - --email-domain=*
        - --skip-provider-button=true
        - --request-logging=true
        - --google-admin-email=t
        - --google-group=d
        - --google-service-account-json=/
        - --cookie-domain=w
        - --cookie-refresh=1h
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180`

I'm sure I would like to remove the "Sign in with a Google Account" step. I succeed by replacing "/sign_in" to "/start" but it doesn't seem proper, right?
    ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"

... I don't understand why "--skip-provider-button" doesn't work :( ?

About the PR you linked, I'm not using "nginx auth_request".

**Comment by ploxiln** [comment]
kubernetes "ingress" "auth-url" is indeed "nginx auth_request".

Replacing "/sign_in" with "/start" is proper if you want the oauth process to start right away without a button.

The `--skip-provider-button` option was originally just for the oauth2_proxy original proxy mode, causing it to load the /start page instead of the /sign_in page when a request fails the auth check. #407 makes oauth2_proxy work for your case where you want to use /sign_in but you want it to do /start because this comes up often for kubernetes users. It may seem un-intuitive, but note that oauth2_proxy was created before kubernetes.

**Comment by Sneko** [comment]
That's a clear explanation! Thank you very much :)
